services:
  app_email:
    build:
      context: "."
      dockerfile: app_email/deployment/agent/Dockerfile
    image: app_email:latest
    container_name: "app_email"
    entrypoint:
      - /bin/entrypoint.sh
    networks:
      - dataverse_ai_nw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_ID=${RESEND_EMAIL_ID}
      - PORT=3001
    ports:
      - "3001:3001"
  mcp_tool_email:
    build:
      context: "."
      dockerfile: app_email/deployment/mcp/Dockerfile
    image: mcp_tool_email:latest
    container_name: "mcp_tool_email"
    entrypoint:
      - /bin/entrypoint.sh
    networks:
      - dataverse_ai_nw
    environment:
      - AGENT_HOST=app_email
      - AGENT_PORT=3001
      - PORT=3002
    ports:
      - "3002:3002"
  app_websearch:
    build:
      context: "."
      dockerfile: app_websearch/deployment/agent/Dockerfile
    image: app_websearch:latest
    container_name: "app_websearch"
    entrypoint:
      - /bin/entrypoint.sh
    networks:
      - dataverse_ai_nw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - PORT=5001
    ports:
      - "5001:5001"
  mcp_tool_websearch:
    build:
      context: "."
      dockerfile: app_websearch/deployment/mcp/Dockerfile
    image: mcp_tool_websearch:latest
    container_name: "mcp_tool_websearch"
    entrypoint:
      - /bin/entrypoint.sh
    networks:
      - dataverse_ai_nw
    environment:
      - AGENT_HOST=app_websearch
      - AGENT_PORT=5001
      - PORT=5002
    ports:
      - "5002:5002"
  agent_fedora:
    build:
      context: "."
      dockerfile: agent_fedora/deployment/agent/Dockerfile
    image: agent_fedora:latest
    container_name: "agent_fedora"
    entrypoint:
      - /bin/entrypoint.sh
    networks:
      - dataverse_ai_nw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MCP_WEBSEARCH_HOST=mcp_tool_websearch
      - MCP_EMAIL_HOST=mcp_tool_email
      - MCP_EMAIL_PORT=3002
      - MCP_WEBSEARCH_PORT=5002
      - PORT=8000
    ports:
      - "8000:8000"
  ui_fedora:
    build:
      context: "."
      dockerfile: agent_fedora/deployment/ui/Dockerfile
    image: ui_fedora:latest
    container_name: "ui_fedora"
    entrypoint:
      - /bin/entrypoint.sh
    networks:
      - dataverse_ai_nw
    environment:
      - AGENT_HOST=agent_fedora
      - AGENT_PORT=8000
      - PORT=8501
    ports:
      - "8501:8501"
networks:
  dataverse_ai_nw: { }
